### ISSUE TITLE
You have to use the original license :)

### ISSUE THREAD

**Issue by RyuuSlayer** [felixvonderladen/b1.7.3-adventurecraft#1]
You have to change the license to be the one from the [original repo](https://github.com/RyuuSlayer/AC-1.7.3). Which as of this day is GPLv3, so you are required to change to that. Otherwise it's straight up stealing that you can be sued for. You'll also have to provide the names of the authors inside of the fabric.mod.json & provide proper acknowledgment of where you got this code from. I highly discourage you from infringing the terms of the license.

**Comment by felixvonderladen** [comment]
First of we both are using code from AdventureCraft itself which is licensed under CC-BY-NO-SA and what this means is that we are forced to use the same license. What I'm gonna change now. And I'm sorry for not adding TechPizza to the fabric.mod.json I forgot that so I'm gonna change that as well. But I don't know what you even Contributed to be honest. Your Contribution is so low that I think you shouldn't deserve any credit. And about that "stealing code" thing. First of all everybody could take the Adventurecraft JAR and do the same as I did and I'm not gonna name how I did it anymore. And the only thing I did was stealing code from TechPizza but I just hope he is a nice person and gets that I don't want to steal his code I just want to work on this project further but on another Repo. I don't have anything against him. And If you are not smart enough at this point to understand that you didn't do shit for this (I'm talking about the work after I reobfuscated the whole code) you should know it now and I wont cooperate with a person that didn't cooperate with me. So go ahead and sue me for something you didn't create or did anything for.
